<a href="https://colab.research.google.com/github/Banty825413/Ml-and-DL-projects-/blob/main/word_embbeding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import tensorflow as tf


In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
# Sentences
sent =['i am good boy',
       'the glass of juice',
       'i am thirsty man',
       'you are brave boy',
       'you are too good'
       ]

In [10]:
voc_size = 10000

In [11]:
# One Hot Representences
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)
#


[[3426, 6949, 1764, 2907], [9831, 5618, 2559, 4199], [3426, 6949, 1739, 264], [7648, 5788, 8198, 2907], [7648, 5788, 7882, 1764]]


In [12]:
# Word Embeding
# we have to decide how many feature we give or dimension

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [13]:
import numpy as np

In [14]:
sent_length = 8    #decide how much length of senctece
embedded_doc=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_doc)


[[   0    0    0    0 3426 6949 1764 2907]
 [   0    0    0    0 9831 5618 2559 4199]
 [   0    0    0    0 3426 6949 1739  264]
 [   0    0    0    0 7648 5788 8198 2907]
 [   0    0    0    0 7648 5788 7882 1764]]


In [15]:
# Considering the dimnesion
dim =10

In [16]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [17]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [18]:
embedded_doc[0]

array([   0,    0,    0,    0, 3426, 6949, 1764, 2907], dtype=int32)

In [19]:
print(model.predict(embedded_doc)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 768ms/step
[[ 0.01851852 -0.01658253 -0.01540546  0.04443089  0.04556098 -0.00763224
  -0.0272939   0.00276621 -0.02060013 -0.03887255]
 [ 0.01851852 -0.01658253 -0.01540546  0.04443089  0.04556098 -0.00763224
  -0.0272939   0.00276621 -0.02060013 -0.03887255]
 [ 0.01851852 -0.01658253 -0.01540546  0.04443089  0.04556098 -0.00763224
  -0.0272939   0.00276621 -0.02060013 -0.03887255]
 [ 0.01851852 -0.01658253 -0.01540546  0.04443089  0.04556098 -0.00763224
  -0.0272939   0.00276621 -0.02060013 -0.03887255]
 [ 0.04249467 -0.02678795  0.00272466 -0.01046991  0.00216172  0.00023309
  -0.04456982 -0.04630518 -0.04751115 -0.04585619]
 [ 0.02233538  0.04468504 -0.01023325 -0.01134119  0.04913691 -0.04876893
  -0.02477796 -0.02305454 -0.00173711 -0.04796188]
 [-0.04583494 -0.00068105 -0.03056951  0.02787082 -0.04677523  0.0326736
   0.01183643  0.0433968   0.02119272  0.02139434]
 [ 0.0260107  -0.01552353  0.01029187 -0.01877345 -0.0374889  -0.02574372
  -0.03135314

Example of using pre_Trained GloVe Embedding


In [23]:
from numpy import array
from numpy import zeros  # to get 0's vector matrix
from numpy import asarray # to convert into array
from tensorflow.keras.preprocessing.text import Tokenizer

from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten

In [21]:
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']

In [24]:
# define class label ,it means define good or bad , like for 'good work' : 1 and 'poor work' : 0
label=array([1,1,1,1,1,0,0,0,0,0])

In [27]:
from numpy._core.defchararray import encode
#Tokenizing Docs
t=Tokenizer()
t.fit_on_texts(docs)
vocab_size=len(t.word_index)+1
encoded_docs=t.texts_to_sequences(docs)
print(encoded_docs)

[[6, 2], [3, 1], [7, 4], [8, 1], [9], [10], [5, 4], [11, 3], [5, 1], [12, 13, 2, 14]]


In [28]:
# Paddig the sentences for max length 4
max_length = 4
padded_docs=pad_sequences(encoded_docs,maxlen=max_length,padding='post')
print(padded_docs)

[[ 6  2  0  0]
 [ 3  1  0  0]
 [ 7  4  0  0]
 [ 8  1  0  0]
 [ 9  0  0  0]
 [10  0  0  0]
 [ 5  4  0  0]
 [11  3  0  0]
 [ 5  1  0  0]
 [12 13  2 14]]


In [33]:
# importing GloVe
!wget https://nlp.stanford.edu/data/glove.6B.zip

--2026-06-16 18:44:39--  https://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2026-06-16 18:44:40--  https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip’

glove.6B.zip        100%[===================>] 822.24M  3.95MB/s    in 5m 15s  

2026-06-16 18:49:56 (2.61 MB/s) - ‘glove.6B.zip’ saved [862182613/862182613]



In [39]:
# Loading the GloVe
embeddings_index = dict()
f = open('/content/glove.6B.100d.txt')
for line in f:
  values =line.split()
  word=values[0]
  coef = asarray(values[1:],dtype='float32')
  embeddings_index[word]=coef
f.close()

In [45]:

print(len(embeddings_index))  #no of words it contain

400000


In [48]:
# Creating the weights matrix
embedding_matrix=zeros((vocab_size,100))
for word,i in t.word_index.items():
  embedding_vector = embeddings_index.get(word)
  if embeddings_index is not None:
    embedding_matrix[i]=embedding_vector

In [49]:
# Define the model
model=Sequential()
e=Embedding(vocab_size,100,weights=[embedding_matrix],input_length=4, trainable=False)
model.add(e)
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [50]:
# compiling the Model
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [51]:
# summarize the model
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │         1,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,500 (5.86 KB)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 1,500 (5.86 KB)

In [52]:
model.fit(padded_docs,label,epochs=50,verbose=0)

In [55]:
# Evaluating the Model
loss, accuracy=model.evaluate(padded_docs,label,verbose=0)
print('Accuracy ' +str(accuracy*100))

Accuracy 100.0
